linters-settings:
  forbidigo:
    forbid:
      - ^print.*$
  goheader:
    template-path: header.tmpl
    values:
      regexp:
        ws: "\\s*"
  goimports:
    local-prefixes: chainguard.dev/apko
  gosec:
    excludes:
      # TODO: review those and remove if possible
      - G115  # integer overflow conversion uint64 -> int

linters:
  enable:
  - asciicheck
  - errcheck
  - errorlint
  - forbidigo
  - gofmt
  - goimports
  - gosec
  - gocritic
  - importas
  - prealloc
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  timeout: 10m
