linters-settings:
  depguard:
    include-go-root: true
    packages:
      - io/ioutil
    packages-with-error-message:
      - io/ioutil: 'ioutil was deprecated in 1.16 (https://go.dev/doc/go1.16#ioutil)'
  forbidigo:
    forbid:
      - ^print.*$
      - '^t\.Error.*$(# forbid t\.Error in favor of using testify\.)?'
      - '^t\.Fatal.*$(# forbid t\.Fatal in favor of using testify\.)?'
  goheader:
    template-path: header.tmpl
    values:
      regexp:
        ws: "\\s*"
  goimports:
    local-prefixes: chainguard.dev/apko

linters:
  enable:
  - asciicheck
  - depguard
  - errcheck
  - errorlint
  - forbidigo
  - gofmt
  - goimports
  - gosec
  - gocritic
  - importas
  - prealloc
  - misspell
  - stylecheck
  - tparallel
  - unconvert
  - unparam
  - unused
  - whitespace
output:
  uniq-by-line: false
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
run:
  issues-exit-code: 1
  timeout: 10m
