project_name: apko
version: 2

before:
  hooks:
    - go mod download

env:
  - COSIGN_YES=true

builds:
- id: apko-build
  binary: apko
  main: ./
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - "386"
    - amd64
    - arm64
  ignore:
    - goos: darwin
      goarch: "386"
  flags:
    - -trimpath
  mod_timestamp: '{{ .CommitTimestamp }}'
  ldflags:
    - -extldflags "-static"
    - "{{ .Env.LDFLAGS }}"

signs:
  - id: apko-cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args: ["sign-blob", "--output-signature", "${signature}", "--output-certificate", "${certificate}", "${artifact}", "--yes"]
    artifacts: all

archives:
- files:
    - LICENSE
  wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  draft: false
  prerelease: true
  name_template: "Release {{ .Tag }}"
