package expandapk

import (
	"archive/tar"
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"

	"chainguard.dev/apko/internal/tarfs"
	"chainguard.dev/apko/pkg/apk/types"
)

func TestPkgInfo(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    *types.PackageInfo
	}{{
		// See example at https://wiki.alpinelinux.org/wiki/Apk_spec
		name: "example",
		content: `
# Generated by abuild 3.9.0-r2
# using fakeroot version 1.25.3
# Wed Jul  6 19:09:49 UTC 2022
pkgname = busybox
pkgver = 1.35.0-r18
pkgdesc = Size optimized toolbox of many common UNIX utilities
url = https://busybox.net/
builddate = 1657134589
packager = Buildozer <alpine-devel@lists.alpinelinux.org>
size = 958464
arch = x86_64
origin = busybox
commit = 332d2fff53cd4537d415e15e55e8ceb6fe6eaedb
maintainer = Example <example+alpine@example.com>
provider_priority = 100
license = GPL-2.0-only
replaces = busybox-initscripts
provides = /bin/sh
triggers = /bin /usr/bin /sbin /usr/sbin /lib/modules/*
# automatically detected:
provides = cmd:busybox=1.35.0-r18
provides = cmd:sh=1.35.0-r18
depend = so:libc.musl-x86_64.so.1
datahash = 7d3351ac6c3ebaf18182efb5390061f50d077ce5ade60a15909d91278f70ada7
`,
		want: &types.PackageInfo{
			Name:             "busybox",
			Version:          "1.35.0-r18",
			Arch:             "x86_64",
			Description:      "Size optimized toolbox of many common UNIX utilities",
			License:          "GPL-2.0-only",
			Origin:           "busybox",
			Maintainer:       "Example <example+alpine@example.com>",
			URL:              "https://busybox.net/",
			Dependencies:     []string{"so:libc.musl-x86_64.so.1"},
			Provides:         []string{"/bin/sh", "cmd:busybox=1.35.0-r18", "cmd:sh=1.35.0-r18"},
			InstallIf:        nil,
			Size:             958464,
			ProviderPriority: 100,
			BuildDate:        1657134589,
			RepoCommit:       "332d2fff53cd4537d415e15e55e8ceb6fe6eaedb",
			Replaces:         []string{"busybox-initscripts"},
			DataHash:         "7d3351ac6c3ebaf18182efb5390061f50d077ce5ade60a15909d91278f70ada7",
			Triggers:         []string{"/bin /usr/bin /sbin /usr/sbin /lib/modules/*"},
		},
	}}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			tw := tar.NewWriter(&buf)
			err := tw.WriteHeader(&tar.Header{
				Name: ".PKGINFO",
				Mode: 0o644,
				Size: int64(len([]byte(tt.content))),
			})
			require.NoError(t, err)
			_, err = tw.Write([]byte(tt.content))
			require.NoError(t, err)
			require.NoError(t, tw.Close())

			controlFs, err := tarfs.New(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
			require.NoError(t, err)

			exp := &APKExpanded{ControlFS: controlFs}

			got, err := exp.PkgInfo()
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			require.Equal(t, tt.want, got)
		})
	}
}
