package types

import (
	"bytes"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestParsePackageInfo(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    *PackageInfo
	}{{
		// See example at https://wiki.alpinelinux.org/wiki/Apk_spec
		name: "example",
		content: `
# Generated by abuild 3.9.0-r2
# using fakeroot version 1.25.3
# Wed Jul  6 19:09:49 UTC 2022
pkgname = busybox
pkgver = 1.35.0-r18
pkgdesc = Size optimized toolbox of many common UNIX utilities
url = https://busybox.net/
builddate = 1657134589
packager = Buildozer <alpine-devel@lists.alpinelinux.org>
size = 958464
arch = x86_64
origin = busybox
commit = 332d2fff53cd4537d415e15e55e8ceb6fe6eaedb
maintainer = Example <example+alpine@example.com>
provider_priority = 100
license = GPL-2.0-only
replaces = busybox-initscripts
provides = /bin/sh
triggers = /bin /usr/bin /sbin /usr/sbin /lib/modules/*
# automatically detected:
provides = cmd:busybox=1.35.0-r18
provides = cmd:sh=1.35.0-r18
depend = so:libc.musl-x86_64.so.1
datahash = 7d3351ac6c3ebaf18182efb5390061f50d077ce5ade60a15909d91278f70ada7
`,
		want: &PackageInfo{
			Name:             "busybox",
			Version:          "1.35.0-r18",
			Arch:             "x86_64",
			Description:      "Size optimized toolbox of many common UNIX utilities",
			License:          "GPL-2.0-only",
			Origin:           "busybox",
			Maintainer:       "Example <example+alpine@example.com>",
			URL:              "https://busybox.net/",
			Dependencies:     []string{"so:libc.musl-x86_64.so.1"},
			Provides:         []string{"/bin/sh", "cmd:busybox=1.35.0-r18", "cmd:sh=1.35.0-r18"},
			InstallIf:        nil,
			Size:             958464,
			ProviderPriority: 100,
			BuildDate:        1657134589,
			RepoCommit:       "332d2fff53cd4537d415e15e55e8ceb6fe6eaedb",
			Replaces:         []string{"busybox-initscripts"},
			DataHash:         "7d3351ac6c3ebaf18182efb5390061f50d077ce5ade60a15909d91278f70ada7",
			Triggers:         []string{"/bin /usr/bin /sbin /usr/sbin /lib/modules/*"},
		},
	}, {
		name: "empty",
		content: `
# Empty file
`,
		want: &PackageInfo{},
	}}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParsePackageInfo(bytes.NewReader([]byte(tt.content)))
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			require.Equal(t, tt.want, got)
		})
	}
}

func TestAsPackage(t *testing.T) {
	controlHash := []byte{0x01, 0x02, 0x03, 0x04}
	size := uint64(123456)

	pkginfo := &PackageInfo{
		Name:             "testpkg",
		Version:          "1.0.0",
		Arch:             "amd64",
		Description:      "A test package",
		License:          "MIT",
		Origin:           "testorigin",
		Maintainer:       "Test Maintainer <test@example.com>",
		URL:              "https://example.com/testpkg",
		Dependencies:     []string{"libc", "libssl"},
		Provides:         []string{"testcmd"},
		InstallIf:        []string{"ifpkg"},
		Size:             2048,
		ProviderPriority: 50,
		BuildDate:        1625078400,
		RepoCommit:       "abcdef1234567890",
		Replaces:         []string{"oldtestpkg"},
		DataHash:         "deadbeef",
		Triggers:         []string{"trigger1", "trigger2"},
	}

	want := &Package{
		Name:             "testpkg",
		Version:          "1.0.0",
		Arch:             "amd64",
		Description:      "A test package",
		License:          "MIT",
		Origin:           "testorigin",
		Maintainer:       "Test Maintainer <test@example.com>",
		URL:              "https://example.com/testpkg",
		Dependencies:     []string{"libc", "libssl"},
		Provides:         []string{"testcmd"},
		InstallIf:        []string{"ifpkg"},
		InstalledSize:    2048,
		ProviderPriority: 50,
		BuildDate:        1625078400,
		RepoCommit:       "abcdef1234567890",
		Replaces:         []string{"oldtestpkg"},
		DataHash:         "deadbeef",
		Triggers:         []string{"trigger1", "trigger2"},

		BuildTime: time.Unix(1625078400, 0).UTC(),
		Checksum:  controlHash,
		Size:      size,
	}

	got := pkginfo.AsPackage(controlHash, size)
	require.Equal(t, want, got)
}
